@baseUrl = http://localhost:3000/api
@contentType = application/json
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZTFmN2RlZjYyZDQ2MDk2OTE2OWE3YSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NjQ5NzQ3MiwiZXhwIjoxNzc2NTI2MjcyfQ.72cfax3Isso0zcuKfPlMSccD3a0rtgXGHIs1d3D8rL4


### Generar Backup de la Base de Datos
POST {{baseUrl}}/admin/backup
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}